// Larica-Angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  title = 'O que você deseja comer hoje';

  constructor() { }

  ngOnInit(): void {
  }

  setTitle (newTitle: string) {
    this.title = newTitle;
  }
}

<app-bodycontent>
  <h2>{{title}}?</h2>
  <app-recipeslist (onInteraction)="setTitle($event)"></app-recipeslist>
</app-bodycontent>

// Larica-Vue/src/Pages/Home/index.vue
<template>
  <BodyContent>
    <h2>{{state.title}}?</h2>
    <RecipeList :setTitle='setTitle'/>
  </BodyContent>
  
</template>

<script>
  import BodyContent from '../../components/bodycontent';
  import RecipeList from '../../components/recipelist';
  import { reactive } from 'vue'; 
  export default {
    name: 'App',
    components: {
      BodyContent,
      RecipeList
    },
    setup(){
      let state = reactive({title:'O que você deseja comer hoje'})

      function setTitle(newTitle){
        state.title = newTitle;
      }

      return {state, setTitle};
    }
  }
</script>
