// Larica-Angular/src/app/ingredientcard/ingredientcard.component.ts
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-ingredientcard',
  templateUrl: './ingredientcard.component.html',
  styleUrls: ['./ingredientcard.component.css']
})
export class IngredientcardComponent implements OnInit {
  @Input() ingredient: String;

  @Output() onInteraction = new EventEmitter<string>();

  emitRemove(toRemoveIngredient) {
    this.onInteraction.emit(toRemoveIngredient);
  }

  constructor() { }

  ngOnInit(): void {

  }

}

<li>
  <button (click)="emitRemove(ingredient)">
    <img src="../../assets/icons/x-mark.svg" alt="remover ingrediente"/>
  </button>
  {{ingredient}}
</li>

// Larica-React/src/components/ingredientcard/index.js
import React from 'react';

import { Container } from './styles';
import XMark from '../../assets/icons/x-mark.svg';

function ingredientCard ({ name, remove }) {
  return (
    <Container>
      <button onClick={remove}>
        <img src={XMark} alt="remover ingrediente"/>
      </button>
      {name}
    </Container>
  );
}

export default ingredientCard;
