// Larica-Svelte/src/Pages/Ingredients.svelte
<BodyContent>
  <h2>Meus ingredientes</h2>
  <IngredientsList />
</BodyContent>
  
<script>
  import BodyContent from '../components/bodycontent/bodycontent.svelte';
  import IngredientsList from '../components/ingredientslist/ingredientslist.svelte';
</script>

<style>
  h2 {
    color: #58B76C;
    font-size: 2rem;
    margin-bottom: 2rem;
    margin-top: 0;
  }
</style>

// Larica-Vue/src/Pages/Ingredients/index.vue
<template>
  <BodyContent>
    <h2>Meus ingredientes</h2>
    <IngredientsList/>
  </BodyContent>

</template>

<script>
  import BodyContent from '../../components/bodycontent';
  import IngredientsList from '../../components/ingredientslist';
   export default {
    name: 'App',
    components: {
      BodyContent,
      IngredientsList
    }
  }
</script>
