// Larica-Svelte/src/App.svelte
<main class="container">
  <HeaderContent/>
  <Home/>
</main>

<script>
  import HeaderContent from './components/header/Header.svelte';
  import Home from './Pages/Home/Home.svelte';
</script>

<style>
  .container{
    padding:0;
    margin:0;
    min-height: 100vh; 
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
</style>

// Larica-Vue/src/App.vue
<template>
  <div id="app">
  <HeaderContent/>
  <router-view/>
  </div>
</template>

<style scoped>

  #app {
    min-height: 100vh; 
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
  
  body {
    -webkit-font-smoothing: antialiased !important;    
  }

  body, input, button {
    font: 14px Montserrat, sans-serif;
  }

</style>

<script>

  import HeaderContent from './components/header';
  export default {
    name: 'App',
    components: {
      HeaderContent
    }
  }

</script>
