// Larica-Angular/src/app/ingredientslist/ingredientslist.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ingredientslist',
  templateUrl: './ingredientslist.component.html',
  styleUrls: ['./ingredientslist.component.css']
})
export class IngredientslistComponent implements OnInit {
  myIngredients: Array<String> = [];


  constructor() { }

  ngOnInit(): void {
  }
  addIngredient(value: String){
    if(value.trim().length > 0){
      this.myIngredients.push(value);
    }
  }
  removeIngredient = (name) =>{
    this.myIngredients = this.myIngredients.filter(ingredient => ingredient !== name);
  }
}


<ul>
  <app-ingredientcard *ngFor="let ingredient of myIngredients" [ingredient]="ingredient" (onInteraction)="removeIngredient($event)"></app-ingredientcard>
  <li>
    <button (click)="addIngredient(newIngredient.value); newIngredient.value='' ">
      <img src="../../assets/icons/plus.svg" alt="adicionar ingrediente"/>
    </button>
    <input #newIngredient type="text" (keyup.enter)="addIngredient(newIngredient.value); newIngredient.value='' " placeholder="Adicionar" />
  </li>
</ul>

// Larica-React/src/components/ingredientslist/index.js
import React, { useState } from 'react';

import IngredientCard from '../ingredientcard';
import { Container } from './styles';

import Plus from '../../assets/icons/plus.svg';

function IngredientsList () {
  const [ingredients, setIngredients] = useState([]);
  const [toAdd, setToAdd] = useState('');

  function removeIngredient(name) {
    setIngredients(ingredients.filter(ingredient => ingredient !== name));
  }

  function addIngredient() {
    if (toAdd.trim().length > 0) {
      setIngredients([...ingredients, toAdd]);
      setToAdd('');
    }
  }

  function handleToAdd(event) {
    setToAdd(event.target.value);
  }

  return (
    <Container>
      {ingredients.map(ingredient => <IngredientCard name={ingredient} key={ingredient} remove={() => removeIngredient(ingredient)}/>)}
      <li className="add">
        <button onClick={addIngredient}>
          <img src={Plus} alt="adicionar ingrediente"/>
        </button>
        <input type="text" placeholder="Adicionar" value={toAdd} onChange={handleToAdd} />
      </li>
    </Container>
  );
}

export default IngredientsList;
