// Larica-Angular/src/app/recipecard/recipecard.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { title } from 'process';

interface Recipe {
  title: string;
  ingredients: string;
  thumbnail: string;
}

@Component({
  selector: 'app-recipecard',
  templateUrl: './recipecard.component.html',
  styleUrls: ['./recipecard.component.css']
})

export class RecipecardComponent implements OnInit {
  @Input() recipe: Recipe;
  @Input() setTitle;

  title;
  ingredients;
  thumbnail;

  constructor() { }

  ngOnInit(): void {
    const { title, ingredients, thumbnail } = this.recipe;

    this.title = title;
    this.ingredients = ingredients;
    this.thumbnail = thumbnail;
  }

}

<li (click)="setTitle(title)">
  <img src={{thumbnail}} alt={{title}} />
  <h3>{{title}}</h3>
  <p>{{ingredients}}</p>
</li>

// Larica-React/src/components/recipecard/index.js
import React from 'react';
import { Container } from './styles';

function recipeCard ({ recipe, setTitle }) {
  const { title, ingredients, thumbnail } = recipe;

  return (
    <Container onClick={() => setTitle(title)}>
      <img src={thumbnail} alt={title} />
      <h3>{title}</h3>
      <p>{ingredients}</p>
    </Container>
  );
}
export default recipeCard;
