// Larica-Vue/src/Pages/Ingredients/index.vue
<template>
  <BodyContent>
    <h2>Meus ingredientes</h2>
    <IngredientsList/>
  </BodyContent>

</template>

<script>
  import BodyContent from '../../components/bodycontent';
  import IngredientsList from '../../components/ingredientslist';
   export default {
    name: 'App',
    components: {
      BodyContent,
      IngredientsList
    }
  }
</script>

// Larica-React/src/Pages/Ingredients/index.js
import React from 'react';

import BodyResult from '../../components/bodyresult';
import IngredientsList from '../../components/ingredientslist';

import Background from '../../assets/background/ingredients.jpg';

function Ingredients() {
  return (
    <BodyResult bgImage={Background}>
      <h2>Meus ingredientes</h2>
      <IngredientsList />
    </BodyResult>
  );
}

export default Ingredients;
